[package]
name = "tokio_example2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
tokio = { version = "1.21", features = ["full"] }

[profile.dev]
opt-level = 0
debug = 2